bookmark/urls.py
''' import django authentication views '''
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'bookmark'

urlpatterns = [
    
    # start authetication path 
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    
    # signup url 
    path('signup/', views.SignupPageView.as_view(), name='signup'),
    # password related paths
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/',auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # end authentication path 
    
    path('', views.home, name='home'),
    path('form/', views.form, name='form'),
    path('form_done/', views.form_done, name='form_done'),
    path('info/', views.info, name='info'),
]

bookmarkapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import debug_toolbar



urlpatterns = [
        # admin_honeypot
        path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
        # django admin 
        path('codinggee/', admin.site.urls),
        
        # user management 
        path('accounts/', include('allauth.urls')),
        
            # local app 
        path('', include('bookmark.urls', namespace='bookmark')),
        path('books/', include('books.urls', namespace='books')),
        path('orders/', include('orders.urls', namespace='orders')),
        path('__debug__/', include(debug_toolbar.urls)),
        
    ] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/urls.py
from django.urls import path
from .views import BookListView, BookDetailView, SearchResultListView


app_name = 'books'

urlpatterns = [
    path('', BookListView.as_view(), name='book-list'),
    path('<uuid:pk>', BookDetailView.as_view(), name="book-detail"),
    path('search/', SearchResultListView.as_view(), name="search-results"),
]

bookmark/models.py
from django.db import models
from django.utils.translation import gettext_lazy  as _
from django.contrib.auth.models import AbstractUser


''' create an abstract User ''' 
class CustomUser(AbstractUser):
    pass

''' Create your models here '''
class BookmarkModel(models.Model):
    # model information for process
    PRIVATE = 'PR'
    PUBLIC = 'PB'
    # create choices dictionary
    URL_CHOICES = [
        (PRIVATE, 'private'),
        ( PUBLIC, 'public'),
    ]
    title = models.CharField(max_length=200)
    url = models.URLField(max_length=200)
    url_choice = models.CharField(max_length=3, choices=URL_CHOICES, default='pick one')
    date = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'boomark'
        ordering = ['title']
        
    def is_upperclass(self):
        return self.url_choice in {
            self.PRIVATE, self.PUBLIC
        }

bookmark/forms.py
''' importing Model form from Django Form '''
from django.forms import ModelForm

''' importing BookmarkModel from Model file '''
from .models import BookmarkModel

''' from django i'm importing usercreationform and userchange form to create the admin user form '''
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

''' import django default user admin model '''
from django.contrib.auth import get_user_model

''' create a custom user admin form '''
class CustomUserCreationForm(UserCreationForm):
    
    '''  use the get_user_model '''
    class Meta:
        model = get_user_model()
        fields = ('email', 'username',)
        
''' create a Custom Use rChange Form '''
class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = ('email', 'username')

'''  Creating Form from ModelForm '''
class BookmarkForm(ModelForm):
    
    class  Meta:
        # call the form model for the form 
        model = BookmarkModel
        # form display
        fields = ['title', 'url', 'url_choice' ]
        

bookmark/views.py
from .forms import BookmarkForm
from django.shortcuts import redirect, render
from .models import BookmarkModel

''' import for form creation '''
from django.urls import reverse_lazy
from django.views import generic
from .forms import CustomUserCreationForm

''' sign up class based view '''
class SignupPageView(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('bookmark:login')
    template_name = 'signup.html'



def home(request):
    name = request.user
    msg = 'Congrats on your first step to becoming a django developer'
    template_name = 'index.html'
    
    return render(
        request, 
        template_name, 
        { 
         'name': name,
         'msg' : msg,
         } )

def form(request):
    template_name = 'form.html'
    msg = 'Please fill in the following...'
    name = 'CodingGee'
    
    if request.method == 'POST':
        form = BookmarkForm(request.POST)
        if form.is_valid():
            form.save()
            # return HttpResponseRedirect('../form_done/')r
            return redirect('bookmark:form_done')
                    
    else:
        form = BookmarkForm()
        
    return render(
        request, 
        template_name,
        {
            'name' : name,
            'msg' : msg,
            'form' : form,
         })
    
def form_done(request):
    form_msg = 'Form Submitted !'
    form_url_done = 'form_done.html'
    return render(
        request, 
        form_url_done,
        {
            'form_msg' : form_msg,
        })

def info(request):
    req_info = BookmarkModel.objects.values().order_by('id')
    msg = 'Saved Bookmark'
    info_template = 'info.html'
    return render(
        request, 
        info_template,
        {
            'req_info' : req_info,
            'msg' : msg,
        })

bookmark/templates/form.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block content %}
    <div class="d-flex justify-content-center m-5">
        <h1 class="fw-bolder">Hello, {{ name }}</h1>
    </div>
    <div class="col border-1">
        <p class="text-center ">{{ msg }}</p>
    </div>
    <div class="d-flex justify-content-center">
        <div class="col-5  mt-3">
            <form action="" method="post">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                {{ hidden }}
                {% endfor %}
    
                {% for field in form.visible_fields %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}" class="mt-3">{{ field.label }}</label>
                    {{ field|add_class:'form-control' }}
                    {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-outline-success mt-4 w-100">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}

bookmark/templates/form_done.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
  <div class="d-flex justify-content-center m-5">
    <h1 class="fw-bolder"> {{ form_msg }} </h1>
  </div>
  <div class="d-flex justify-content-center mt-3">
    <strong>Click <a class="text-warning text-decoration-none" href="{% url 'bookmark:info' %}">here</a> to proceed to view saved bookmark</strong>
  </div>
  <p class="text-center"> go <a class="text-success fw-bold text-decoration-none" href="{% url 'bookmark:home' %}">home </a></p>
{% endblock %}

bookmark/templates/index.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
  <div class="col-12 d-flex justify-content-center">
    {% if user.is_authenticated %}
    <p class="mx-3">Hi, {{ user.email }}</p>
    <p><a href="{% url 'account_logout' %}">Log Out</a></p>
    {% else %}
    <p class="text-success p-2">We've missed you! <a class="text-decoration-none" href="{% url 'account_login' %}">Sign in</a></p>
    <p class="text-warning p-2"><a class="text-decoration-none" href="{% url 'account_signup' %}">Sign up</a></p>
    {% endif %} 
  </div>
  {% if user.is_authenticated %}
  <div class="d-flex justify-content-center m-5 ">
    <h1 class="fw-bolder text-sm-success">Hello, {{ name }}</h1>
  </div>
  <div class="d-flex justify-content-center mt-3">
    <strong class="text-sm-success">Click <a class="text-warning" href="{% url 'bookmark:form' %}">here</a> to proceed to the form...</strong>
  </div>
  {% else %}
  <div class="d-flex justify-content-center m-5 ">
    <h1 class="fw-bolder text-sm-success">Search for Django Books</h1>
  </div>
  <div class="d-flex justify-content-center">
    <div class="col-lg-5">
      <form class="form-inline mt-2 mt-md-0" action="{% url 'books:search-results' %}" method="get">
        <input name="q" class="form-control mr-sm-2" type="text" placeholder="Search"
        aria-label="Search">
      </form>
    </div>
  </div>
  <div class="d-flex justify-content-center mt-3">
    <strong class="text-sm-success">Get Started...</strong>
  </div>
  {% endif %} 
  <div class="d-flex justify-content-center m-5">
    <div class="modal" tabindex="-1" id="myModal">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title text-success">Congrats</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <p>{{ msg }}.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

bookmark/templates/info.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
  <div class="d-flex justify-content-center m-5">
    <h1 class="fw-bolder text-warning"> {{ msg}} </h1>
  </div>
  <div class="mt-3">
    <p class="text-center fw-bold">Click to return <a class="text-danger text-decoration-none"
        href="{% url 'bookmark:home' %}">Home</a></p>
  </div>
  <div class="d-flex justify-content-center m-5 col-10">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Bookmark Title</th>
          <th scope="col">Bookmark </th>
          <th scope="col">Choices </th>
          <th scope="col">Bookmark Date</th>
        </tr>
      </thead>
      <tbody>
        {% for info in req_info %}
        <tr>
          <th scope="row">{{ info.id }}</th>
          <td>{{ info.title }}</td>
          <td>{{ info.url }} </td>
          <td>{{ info.url_choice }} </td>
          <td>{{ info.date }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
 {% endblock %}