bookmarkapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import debug_toolbar



urlpatterns = [
        # admin_honeypot
        path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
        # django admin 
        path('codinggee/', admin.site.urls),
        
        # user management 
        path('accounts/', include('allauth.urls')),
        
            # local app 
        path('', include('bookmark.urls', namespace='bookmark')),
        path('books/', include('books.urls', namespace='books')),
        path('orders/', include('orders.urls', namespace='orders')),
        path('__debug__/', include(debug_toolbar.urls)),
        
    ] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/urls.py
from django.urls import path
from .views import BookListView, BookDetailView, SearchResultListView


app_name = 'books'

urlpatterns = [
    path('', BookListView.as_view(), name='book-list'),
    path('<uuid:pk>', BookDetailView.as_view(), name="book-detail"),
    path('search/', SearchResultListView.as_view(), name="search-results"),
]

orders/urls.py
from django.urls import path
from . import views 

app_name = 'orders'

urlpatterns = [
    path('charge/',views.charge, name='charge'),
    path('', views.OrdersPageView.as_view(), name='orders'),
   
]

orders/models.py
from django.db import models

# Create your models here.

orders/views.py
from django.contrib.auth.models import Permission
from django.shortcuts import render
from django.conf import settings
import stripe


# Create your views here.
from django.views.generic.base import TemplateView

class OrdersPageView(TemplateView):
    template_name = 'orders/purchase.html'
    
    # getting pblic ke for strip and passing it in the template 
    # overiding get_context_data()
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['stripe_key'] = settings.STRIPE_TEST_PUBLISHABLE_KEY
        return context
    
    
# stripe api key
stripe.api_key = settings.STRIPE_TEST_PUBLISHABLE_KEY

# charge view 
def charge(request):
    # Get the permission 
    permission = Permission.objects.get(codename='special_status')
    
    # get the user
    u = request.user
    # add user permission 
    u.user_permissions.add(permission)
    if request.method == "Post":
        stripe.Charge.create(
            amount = 3900,
            currency='usd',
            description='Purchase all books',
            source=request.POST['stripeToken']
        )
    return render(request, 'orders/charge.html', )

orders/templates/orders/charge.html
{% extends 'base/base.html' %}
{% block title %}Charge{% endblock title %}
{% block content %}
<h2>Thank you for your order! You now have access to
<a href="{% url 'books:book-list' %}">All Books</a>.</h2>
{% endblock content %}

orders/templates/orders/purchase.html
{% extends 'base/base.html' %}
{% block title %}Orders{% endblock title %}
{% block content %}
<h1>Orders page</h1>
<p>Buy for $39.00</p>

<form action="{% url 'orders:charge' %}" method="post">
    {% csrf_token %}
    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="{{ stripe_key }}"
        data-description="All Books"
        data-amount="3900"
        data-locale="auto">
    </script>
</form>
{% endblock content %}