bookmarkapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import debug_toolbar



urlpatterns = [
        # admin_honeypot
        path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
        # django admin 
        path('codinggee/', admin.site.urls),
        
        # user management 
        path('accounts/', include('allauth.urls')),
        
            # local app 
        path('', include('bookmark.urls', namespace='bookmark')),
        path('books/', include('books.urls', namespace='books')),
        path('orders/', include('orders.urls', namespace='orders')),
        path('__debug__/', include(debug_toolbar.urls)),
        
    ] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/urls.py
from django.urls import path
from .views import BookListView, BookDetailView, SearchResultListView


app_name = 'books'

urlpatterns = [
    path('', BookListView.as_view(), name='book-list'),
    path('<uuid:pk>', BookDetailView.as_view(), name="book-detail"),
    path('search/', SearchResultListView.as_view(), name="search-results"),
]

orders/urls.py
from django.urls import path
from . import views 

app_name = 'orders'

urlpatterns = [
    path('charge/',views.charge, name='charge'),
    path('', views.OrdersPageView.as_view(), name='orders'),
   
]

books/models.py
from django.db import models
''' import uuid for id protection and slug error '''
import uuid

''' import reverse to add a canonical URL '''
from django.urls import reverse

from django.contrib.auth import get_user_model

# Create your models here.
class Book(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    cover = models.ImageField(upload_to='cover/', blank=True)
    
    class Meta:
        permissions = [
            ('special_status', 'Can read all books')
        ]
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("books:book-detail", args=[str(self.id)])
    
class Review(models.Model):
    book = models.ForeignKey(
        Book,
        on_delete=models.CASCADE,
        related_name='reviews'
    )
    review = models.CharField(max_length=255)
    author = models.ForeignKey(get_user_model(),
                               on_delete=models.CASCADE)
    def __str__(self):
        return self.review
    

books/views.py
''' importing loginrequiredmixin '''
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
''' using generic listview '''
from django.views.generic import ListView, DetailView

''' import Book model  '''
from .models import Book

''' import Q for filtering books '''
from django.db.models import Q 

from django.shortcuts import render

# Create your views here.
class BookListView(LoginRequiredMixin, ListView):
    model = Book
    context_object_name = 'book_list'
    template_name = 'books/book_list.html'
    login_url = 'account_login'
    
class BookDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Book
    context_object_name = 'book'
    template_name = 'books/book_detail.html'
    login_url = 'account_login'
    permission_required = 'books.special_status'
    
class SearchResultListView(ListView):
    model = Book
    context_object_name = 'book_list'
    template_name = 'books/search-results.html'
    
    def get_queryset(self):
        query = self.request.GET.get('q')
        return Book.objects.filter(
            Q(title__icontains=query) | Q(author__icontains=query)
        )

books/templates/books/book_detail.html
{% extends 'base/base.html' %}
{% block title %}{{ object.title }}{% endblock title %}
{% block content %}
<div class="container">
    <div class="book-detail">
        {% if book.cover %}
        <img class="mt-3" src="{{ book.cover.url }}" alt="{{ book.title }}">
        {% endif %}
        <h2><a class="text-decoration-none" href="">{{ book.title }}</a></h2>
        <p>Author: {{ book.author }}</p>
        <p>Price: {{ book.price }}</p>
        <div>
            <h3>Reviews</h3>
            <ul class="">
                {% for review in book.reviews.all %}
                <li>{{ review.review }} <blockquote>({{ review.author }}) </blockquote></li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock content %}

books/templates/books/book_list.html
{% extends 'base/base.html' %}
{% block title %}Books{% endblock title %}
{% block content %}

{% include "nav/nav.html" %}
{% if not perms.books.special_status %}
<div class="container mt-4 mx-md-4 mb-2">
    <a href="{% url 'orders:orders' %}" class="btn btn-success" >Purchase All Books</a>
</div>
{% endif %}

<!-- write a for loop, looping through each book titles -->
{% for book in book_list %}
<div>
    <div class="container">
        <h2 class="mx-3"><a class="text-decoration-none" href="{{ book.get_absolute_url }}">{{ book.title }}</a></h2>
    </div>
</div>
{% endfor %}
{% endblock content %}

books/templates/books/search-results.html
<!-- templates/books/search_results.html -->
{% extends 'base/base.html' %}
{% block title %}Search{% endblock title %}
{% block content %}
<div class="container">
    <h1>Search Results</h1>

    {% for book in book_list %}
    <div>
        <div class="container">
            <h2 class="mx-3"><a class="text-decoration-none" href="{{ book.get_absolute_url }}">{{ book.title }}</a></h2>
            <p>Author: {{ book.author }}</p>
            <p>Price: $ {{ book.price }}</p>
        </div>
    </div>
    {% endfor %}
</div>


{% endblock %}